# Generated by Django 2.2 on 2020-10-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
