# Generated by Django 2.2 on 2020-10-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0002_auto_20201021_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
