# Generated by Django 2.2 on 2020-10-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0003_auto_20201022_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nick',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
