# Generated by Django 2.2 on 2020-10-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0004_auto_20201022_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.AddField(
            model_name='customuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_room.Room'),
        ),
    ]
