# Generated by Django 2.2 on 2020-10-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0005_auto_20201022_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
