# Generated by Django 2.2 on 2020-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0006_room_invite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='invite_link',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
