# Generated by Django 2.2 on 2020-10-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
